### ISSUE TITLE
MultiPlus resets when I connect my MAX485 adapter

### ISSUE THREAD

**Issue by kinsi55** [pv-baxi/esp32ess#1]
I'm currently trying to figure out how to integreate the MultiPlus into my existing PV Setup (Needing to tell it how much to produce) - This codebase will be a big help for that once I get to actually writing code but I'm stuck at connecting it up. I've modified my MAX485 adapter according to the instructions (Removed R5, R6, R7) and soldered an RJ45 cable to it. I am using an external powersource so I only grab Ground, A and B from the MultiPlus and connected those to my MAX485 board.

Having nothing else connected (Besides the MK3-USB), as soon as I connect the (unpowered) board to the MultiPlus the VEConfigure connection just drops and eventually the LEDS on the MultiPlus all blink and it resets.

I've triplechecked the pinout and I am pretty sure it must be correct (With the RJ45 lock on the left, starting from the third pin from the top: GND, A, B)

I have measured resistances, A to B is 45k, and A/B to GND is 27k - I'm kinda confused at this point, if you have any idea I'd appreciate that.

**Comment by pv-baxi** [comment]
Hi Kinsi,
all what you did sounds right, so unfortunately I don't immediately know where your problem is.

According to my experience: The multiplus resets as soon as the bus is "blocked" for a too long period. So it constantly listens to its own output frames and as soon as too many of those frames are not readable anymore, it resets for safety reasons.

I had the same problem quite often when I reprogrammed my ESP32 via USB. Because while programming the output pins of the ESP32 are sometimes in an undefined state. I could solve the problem by adding a 1kOhm resistor from Gnd to the input of the level translator controlling the DE+RE pins on the MAX485 board. Note that you have to do this in front of the level translator at the ESP32 side, NOT in the 5V domain.
This has the effect that whenever the output pin of the ESP32 is in high-impedance or undefined state, the 1k resistor will pull it to Gnd, putting the MAX485 into read/listening mode, which is safe.

Maybe the problem just arises from the fact that your board has no power yet. This might also result in a high-impedance state, similar to my situation.

Hope it helps, Baxi

**Comment by kinsi55** [comment]
You say Level Translator / Level Shifter - Why do you happen to use one? You're powering the MAX485 off 3.3V and the ESP is a 3.3V chip, whats the purpose of the Level Shifter here?

**Edit:** I've figured out my issue... Seems like it is the MK3. If I disconnect the MK3 and *only* have my MAX485 connected it works perfectly fine - If I have both connected I also seem to correctly receive the communication in my code (at first), but yeah after a couple of seconds the MultiPlus just starts blinking LEDs and quits.

Not an issue for me since I dont need the MK3 (Would've been good to test stuff) but probably good to know nontheless (Or can I not just passively read in this case and *have to* acknowledge stuff?)

**Comment by kinsi55** [comment]
Ok so I have adapted your code into my own implementation (At the end of comment fwiw), the ESS commands I send are acknowledged / 0x87 response, however the AC output is unaffected. In my setup I just use a 54V powersupply as my "battery" but that shouldnt matter(?)

With the MP2 and PSU connected the MP2 successfully synchronizes and connects to the mains, however me changing the setpoint has no effect, neither on powerdraw nor production - One observation is that the Bulk LED of the MP2 lights up, eventho I have turned off the charger of the MP2 - does the ESS have its own seperate charger?

In your code you use 0x83 as the Command ID, which is 131 - According to [the Victron manual however](https://www.victronenergy.com/live/ess:ess_mode_2_and_3), the first assistants ram0's ID would be 129 - It it just a coincidence that these values are close to each other / both make sense or is one of the two outdated here? FWIW I updated my MP2 to the latest firmware.

Thank you

> Changing setpoint to 60
> Sending Command with ID: 70 - 98 F7 FE 46 00 E6 37 02 83 3C 00 DF FF
> CMD ACK: 87
> Changing setpoint to 0
> Sending Command with ID: 58 - 98 F7 FE 3A 00 E6 37 02 83 00 00 27 FF
> CMD ACK: 87

Code is unfinished, the parsing of received stuff is ofc not fault proof at all but is fine for testing purposes. One thing I noticed is that it doesnt matter what frame number I send, I still get 0x87 back - Shouldnt the MP2 ignore commands with an incorrect frame number?

```#include <Arduino.h>
#include "driver/uart.h"

#define VEBUS_RX 26
#define VEBUS_TX 25
#define VEBUS_DE 27

void setup() {
  Serial.begin(115200);
  Serial1.begin(256000, SERIAL_8N1, VEBUS_RX, VEBUS_TX, false, 5);

  Serial1.setPins(-1, -1, -1, VEBUS_DE);
  uart_set_mode(UART_NUM_1, UART_MODE_RS485_HALF_DUPLEX);
}

uint8_t queuedCommand[255];
uint8_t queuedCommandChecksum = 0;
uint8_t queuedCommandSize = 0;

bool appendToCommand(uint8_t* data, uint8_t dataLen, bool isEnd = false) {
  if(queuedCommandSize + dataLen * 2 > sizeof(queuedCommand)) {
    queuedCommandSize = 0;
    return false;
  }

  #define ADDBYTE(_b) \
    queuedCommand[queuedCommandSize++] = _b; \
    queuedCommandChecksum -= _b;

  // https://github.com/pv-baxi/esp32ess/blob/main/docs/README.md#checksum-calculation
  uint8_t byteRangeToReplace = isEnd ? 0xFB : 0xFA;
  while(dataLen-- > 0) {
    uint8_t b = *data++;

    if(b >= byteRangeToReplace) {
      b = 0x70 | (b & 0x0F);
      ADDBYTE(0xFA);
    }

    ADDBYTE(b);
  }

  return true;
}

bool prepareCommand(uint8_t* cmdData, uint8_t cmdLen) {
  if(queuedCommandSize != 0)
    return false;

  queuedCommand[queuedCommandSize++] = 0x98;
  queuedCommand[queuedCommandSize++] = 0xF7;
  queuedCommand[queuedCommandSize++] = 0xFE;
  // The Cmd ID will get added later, just before sending, when finishCommand() is called
  queuedCommand[queuedCommandSize++] = 0;

  queuedCommandChecksum = 1 - queuedCommand[2];

  return appendToCommand(cmdData, cmdLen);
}

int finishCommand(uint8_t lastFrameNum) {
  if(queuedCommandSize == 0)
    return -1;

  auto newCommandId = (lastFrameNum + 1) & 0x7F;

  queuedCommand[3] = newCommandId;
  queuedCommandChecksum -= newCommandId;

  appendToCommand(&queuedCommandChecksum, 1, true);
  queuedCommand[queuedCommandSize++] = 0xFF;

  return newCommandId;
}

bool queueESSCommand(int16_t power, bool persist = false) {
  if(power < 0)
    return false;

  uint8_t x[] = {
    0x00,                 // our own ID
    0xE6,                 // our own ID
    0x37,                 // CommandWriteViaID
    0x02,                 // Flags, 0x02=RAMvar and no EEPROM
    0x83,                 // ID = address of ESS power in assistant memory
    (uint8_t)power,       // Lo value of power (positive = into grid, negative = from grid)
    (uint8_t)(power >> 8) // Hi value of power (positive = into grid, negative = from grid)
  };

  return prepareCommand(x, sizeof(x));
}

uint8_t readBuffer[32];
uint8_t readBufferPos = 0;

void handleInput() {
  if(!Serial.available())
    return;

  char read = Serial.read();

  short setpoint = 0;

  if(read == '0') {
    setpoint = 0;
  } else if(read == '6') {
    setpoint = 60;
  } else {
    return;
  }

  Serial.printf("Changing setpoint to %i\n", setpoint);
  queueESSCommand(setpoint);
}

void loop() {
  handleInput();

  while(Serial1.available() > 0) {
    uint8_t c = Serial1.read();

    readBuffer[readBufferPos++] = c;

    if(c != 0xFF && readBufferPos != 31)
      continue;

    uint8_t frNum = readBuffer[3];

    //Serial.printf("CMD ID: %i\n", frNum);

    if(queuedCommandSize != 0) {
      Serial.printf("Sending Command with ID: %i - ", finishCommand(frNum));

      for(auto i = 0; i < queuedCommandSize; i++)
        Serial.printf("%02X ", queuedCommand[i]);

      Serial.println();

      Serial1.write(queuedCommand, queuedCommandSize);
      queuedCommandSize = 0;
    }

    if(readBuffer[2] == 0xFE && readBuffer[4] == 0x00 && readBuffer[5] == 0xE6) {
      if(readBuffer[6] == 0x85) {
        Serial.printf("ACPower: %i\n", 256 * readBuffer[10] + readBuffer[9]);
      } else {
        // ACK Frame
        Serial.printf("CMD ACK: %02X\n", readBuffer[6]);
      }
    } else {
      // Serial.printf("Unknown Message(%i):", readBufferPos);

      // for(auto i = 0; i < readBufferPos; i++)
      //   Serial.printf("%02X ", readBuffer[i]);

      // Serial.println();
    }
    readBufferPos = 0;
  }
}
```

**Comment by pv-baxi** [comment]
> You're powering the MAX485 off 3.3V and the ESP is a 3.3V chip, whats the purpose of the Level Shifter here?

No, the MAX485 is a 5V chip. So you should power it from the 5V pin of the EPS32 board. As the ESP32 is not 5V input tolerant, I used the level translator. It might still work if powered from 3.3V, but could result in unknown strange effects like in your case that you cannot connect your MAX485 and the MK3 in parallel. I know that this should work because I did this many times in the beginning of my project to sniff the VE.bus communication.

> Or can I not just passively read in this case and _have to_ acknowledge stuff?

When passively reading e.g. MK3 communiction you don't have to acknowledge anything.

> are acknowledged / 0x87 response, however the AC output is unaffected

Things to consider:
- After firmware update, did you program the ESS Assistant into your MP2 using VEconfig? And are you sure your voltage thresholds and battery profile is correct matching your PSU? Because the ESS assistant decides based on your voltage configuration if your "battery" is full (then it will not charge anymore) or empty (then it will not discharge anymore).
- The MP2 needs the ESS value (setpoint) every 10 seconds again. If there is no continious re-send, it will stop producing power or charging after 15 seconds. This is for sure a safety feature.
- If you are in charger-only mode, either using the mains switch or a software command, the reaction time of the MP2 becomes very slow (~30..60 seconds). I have the feeling that in charger-only mode the MP2 want's to be absolutely sure the setpoint is not fluctuating and really stays negative before it starts charging. In normal charger+inverter mode the MP2 reacts much faster.
- The MP2 is not very accurate with "low" power, like 30W or less. Probably because it's internal measurement is inaccurate then, and it needs to measure longer to gain the required precision. So maybe it actually started delivering, but it took longer than the 15 seconds for you to notice, and then it already turned off again.
- Which ACout connection did you use? On ACout2 you should be able to attach a low-power consumer (like an LED bulb) and see the power on your PSU going up. This is independent of your setpoint value. On ACout2 the MP2 simply works as an inverter trying to the deliver the power that is required. If you have ACin connected to mains, using the continious setpoint command you should be able to source or sink power from/into mains. So you need so kind of power meter in between to see the effect.


> One observation is that the Bulk LED of the MP2 lights up, eventho I have turned off the charger of the MP2

Bulk is always on as soon as the ESS assistant is active. It's also on if you source power into the grid (and don't charge). However, as soon as you source power into grid, the inverter LED should turn on additionally. The inverter and charger in the MP2 is the same circuit. So it can either charge or invert, but never both at the same time. BTW, how did you turn off the charger?

> In your code you use 0x83 as the Command ID, which is 131 - According to [the Victron manual however](https://www.victronenergy.com/live/ess:ess_mode_2_and_3), the first assistants ram0's ID would be 129 - It it just a coincidence that these values are close to each other / both make sense or is one of the two outdated here?

The command ID is 0x37 (CommandWriteViaID). The 0x83 = 131 is the RAM ID. So that is no coincidence :-) But unlike stated in the old Victron manual, the power setpoint is not the first RAM ID but 131 instead.

> One thing I noticed is that it doesnt matter what frame number I send, I still get 0x87 back - Shouldnt the MP2 ignore commands with an incorrect frame number?

That's strange. The frame number must definitely match. Otherwise it will not work. I noticed this so many times in my past experiments that I'm absolutely sure. Of course it could be that it is not checked anymore in the latest firmware version. But I don't believe so as checking the correct frame number is an important safety feature. In case its currently not checked, this would be a fimware bug from my point of view.

One thing I noticed in your code:
You're not checking explicitly for (frame[6] == 0x87) in the acknowledgement. How are you sure it's not an error reply like 0x80 (Command not supported)? For explanation of the CommandWriteViaID command and its responses, see
https://www.victronenergy.com/upload/documents/Technical-Information-Interfacing-with-VE-Bus-products-MK2-Protocol-3-14.pdf
on page 22.

**Comment by kinsi55** [comment]
Thank you for your time and detailed response!

> It might still work if powered from 3.3V, but could result in unknown strange effects like in your case that you cannot connect your MAX485 and the MK3 in parallel.

I have tried it with 5V instead and the MP2 still dies when both are connected

FWIW: The ESP**32** is (inofficially) 5V tolerant - it *can* lead to side effects if you apply 5V to pins that support analog but it will survive it / it doesn't cause damage, its just oddities like Wifi not working.

- ~~Yes I have reprogrammed the MP2 after updating and the voltage range is "compatible" (battery low is blinking / pre-warn but with no mains connected it was inverting / output to ac out 1). I do not want to do any charging via the MP2 as my battery is connected to MPPT Charge Controllers.~~
- ~~i have heard of that being a thing, in my test I have sent different setpoints various times~~
- ~~I was in normal operation mode as far as the switch is concerned and haven't done any software changes to make it charger only~~
- ~~in my test I switched back and forth between 0 and 60W and observed no change in grid energy flow (external meter), it stuck around 15W - If that was positive or negative I don't know as it was just a general watt meter, I assume positive~~

> However, as soon as you source power into grid, the inverter LED should turn on additionally

The inverter LED was and stayed on throughout my test (I waited for it to synchronize and connect mains ofc)

> BTW, how did you turn off the charger?

I turned off the Charger in VEConfig - Its turned on when you setup the ESS Assistant, but it won't complain when you manually turn it off after, just like I have with the Battery Monitor / SOC

> the power setpoint is not the first RAM ID but 131 instead.

~~Would that mean the value after, so 0x84, would be the one where I can enable / disable charging / discharging seperately?~~

As for frame num: I tried both +0 and -1 to the last received framenum and both were accepted in my case

> You're not checking explicitly for (frame[6] == 0x87) in the acknowledgement

I print frame[6] to Serial and observed that (See my log output before the code)

### Edit

Ok I think I figured out what is going wrong in my case. I disconnected my ESP and connected the MK3 w/ VictronConnect to get an idea whats going on. When my PSU is set to 54V (Above my low threshold) and mains is connected Bulk is **not** on, when I lower the voltage tho eventually the MP2 will try to "charge my PSU" which will then immediately make it shutdown itself due to OVP (The PSU, I'm testing with an industrial PSU here and it shutting down isn't immediately obvious without me measuring the output Voltage). So I was probably telling the MP2 to feed energy into the grid while the PSU isn't on.

So the question now would be if I can prevent the MP2 from charging the Battery **no matter what**.

### Edit 2

I *thought* I had found a solution by just setting the Charge / Absorbtion Voltage to 48V but that only works as long as I do not send a setpoint - Once I do it switches back to bulk and my PSU turns off again. I guess the ESS has its own logic for charging that I need to override (Possibly by targetting 0x84?)

### Edit 3 (Finale)

Yeah ok I think testing this with a powersupply just simply is not possible at all. I tried setting bit 0 of 0x84 to 1 which *should* disable charging, but according to the linked manual `Important: Disabling charge will also disable feedback.` - So charging always has to at least be possible (Even with that bit set, my PSU still dies when I make the MP2 feed into grid), even if not used. I guess I'll have to hook it up to my battery to test, I'm assuming the code is gonna work fine because the fault case always kicks in once I tell it to feed into the grid.

Thanks for all the help

**Comment by pv-baxi** [comment]
Thanks for your update. Nice to hear that you figured out the issue. I guess the behaviour has to do with the fact that in the MP2, charging and discharging is basically the same. So probably the MP2-internal regulation loop needs to be able to charge, at least for a tiny moment, in order regulate its PWM signals to zero power. That's probably also the reason for the delayed behaviour of the "charge-only" mode.

Apart from that, I'm still wondering about the fact that the frame number does not seem to matter. I'm happy that my ESP32ESS is currently working fantastic, that's why I don't want to upload and reboot it now. But when I make the next code change, I will try out what happens if I use the wrong frame number ;-)

PS: Why don't you simply hook-up your MP2 to the battery in parallel to your MPPTs, also for testing? Such a system setup is absolutely common. My neighbour has it for example. When you source energy while the MPPTs are charging, some of the current will flow into the MP2 and the battery is simply charged with less current. Of course, battery voltage needs to match the MP2, but I guess that was intended usecase anyway.

**Comment by kinsi55** [comment]
My battery isn't close to my PC so testing / setting up with mains is just easier, no other reason really. I have a functioning inverter + control system setup, just gonna swap out for the MP2 once its control is working

**Comment by kinsi55** [comment]
Small Update: I tried it with my battery and it does indeed work. One observation is that it ignores negative setpoints since I have disabled the Charger in VEConfigure, may or may not be a bug with my code rather than being related to having disable the charger but thats what I noticed.

I have not tried if it will *actually* accept setpoints sent with a random frame number, I'll check that when I have actually mounted it in place - If I can just transmit all setpoints with frame number 0 that obviously makes the Code even simpler / removes the need for reading anything at all (Assuming one doesnt care about the acks)

Feel free to adapt my code to your liking if you want to, I believe its much less redundant / clearer - Your code scared me away a bit at first because it seemed really complex :D Since I only send out commands right after receiving an incoming message it should also essentially work 100% of the time

Thanks for everything

**Comment by kinsi55** [comment]
One more question if you dont mind:

Now that I have the MP2 in use I noticed a problem: after running for a while (With no ESS commands because I'm already feeding in via another Microinverter during the day), at some point low feed in setpoints are extremely inaccurate. Say I tell the MP2 to produce 50 Watts, it will instead ramp up to 300-400.

When that happens I can instantly fix it by restarting the MP2, or by waiting 20-30 minutes - It seems like the MP2 has to "recalibrate" or something like that to be able to accurately produce low setpoints, have you noticed this yourself?

**Comment by pv-baxi** [comment]
I noticed a similar behaviour. The MP2 in general is not good in producing low power. Then it takes quite a while to become accurate.You said „after running for a while (With no ESS commands“I don‘t do that. I always send the MP2 an ESS value, every 5 seconds at least. If I want 0W at ACin, I just send 0W ESS commands.But even then the MP2 takes some seconds until the output adjusted to average 0W. With high powers it‘s way more accurate.I guess if you don‘t send commands, it goes in some kind of „safety mode“ from where adaptation might take longer again. This probably comes from the fact that in „safety mode“ it‘s not allowed to produce anything, so it also cannot continue adaptation.Am 19.09.2024 um 19:14 schrieb Kinsi ***@***.***>:﻿
One more question if you dont mind:
Now that I have the MP2 in use I noticed a problem: after running for a while (With no ESS commands because I'm already feeding in via another Microinverter), at some point low feed in setpoints are extremely inaccurate. Say I tell the MP2 to produce 50 Watts, it will instead ramp up to 300-400.
When that happens I can instantly fix it by restarting the MP2, or by waiting 20-30 minutes - It seems like the MP2 has to "recalibrate" or something like that, have you noticed this yourself?

**Comment by kinsi55** [comment]
I see, thank you. When not sending ESS commands the MP2 turns off the Inverter, I do that instead of sending 0W because that ofc saves power.

**Comment by pv-baxi** [comment]
I can fully understand that reason. Does it maybe react faster if you switch it into Standby-Mode instead, using that specific command. I‘m using that command in my code to put it into Charge-Only mode when my battery level is < 15%.
But I fear it will not help and adapting to 50W will take as long as from „safety-mode“.
